var helpInfo = [
    {
        "title":"什么是拼邮",
        "content":"拼邮就是省运费、交朋友！由会员(团长)发起，同城会员(团员)参与抱团，团长和团员的包裹合并为一个大包裹，发货到团长那里，由团长分发给团员。"
    },
    {
        "title":"拼邮的好处",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    },
    {
        "title":"",
        "content":""
    }
]